# Generated by Django 4.0.3 on 2022-09-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicfes_app', '0002_tiket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
