# Generated by Django 4.0.3 on 2022-09-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicfes_app', '0003_alter_reserve_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tiket',
        ),
    ]
